# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/feler/Desarrollo/ceres

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/feler/Desarrollo/ceres

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feler/Desarrollo/ceres/CMakeFiles /home/feler/Desarrollo/ceres/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feler/Desarrollo/ceres/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ceres

# Build rule for target.
ceres: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ceres
.PHONY : ceres

# fast build rule for target.
ceres/fast:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/build
.PHONY : ceres/fast

PyC.o: PyC.c.o
.PHONY : PyC.o

# target to build an object file
PyC.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/PyC.c.o
.PHONY : PyC.c.o

PyC.i: PyC.c.i
.PHONY : PyC.i

# target to preprocess a source file
PyC.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/PyC.c.i
.PHONY : PyC.c.i

PyC.s: PyC.c.s
.PHONY : PyC.s

# target to generate assembly for a file
PyC.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/PyC.c.s
.PHONY : PyC.c.s

atoms/atoms.o: atoms/atoms.c.o
.PHONY : atoms/atoms.o

# target to build an object file
atoms/atoms.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/atoms/atoms.c.o
.PHONY : atoms/atoms.c.o

atoms/atoms.i: atoms/atoms.c.i
.PHONY : atoms/atoms.i

# target to preprocess a source file
atoms/atoms.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/atoms/atoms.c.i
.PHONY : atoms/atoms.c.i

atoms/atoms.s: atoms/atoms.c.s
.PHONY : atoms/atoms.s

# target to generate assembly for a file
atoms/atoms.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/atoms/atoms.c.s
.PHONY : atoms/atoms.c.s

ceres.o: ceres.c.o
.PHONY : ceres.o

# target to build an object file
ceres.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/ceres.c.o
.PHONY : ceres.c.o

ceres.i: ceres.c.i
.PHONY : ceres.i

# target to preprocess a source file
ceres.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/ceres.c.i
.PHONY : ceres.c.i

ceres.s: ceres.c.s
.PHONY : ceres.s

# target to generate assembly for a file
ceres.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/ceres.c.s
.PHONY : ceres.c.s

client.o: client.c.o
.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i
.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s
.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/client.c.s
.PHONY : client.c.s

color.o: color.c.o
.PHONY : color.o

# target to build an object file
color.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/color.c.o
.PHONY : color.c.o

color.i: color.c.i
.PHONY : color.i

# target to preprocess a source file
color.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/color.c.i
.PHONY : color.c.i

color.s: color.c.s
.PHONY : color.s

# target to generate assembly for a file
color.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/color.c.s
.PHONY : color.c.s

draw.o: draw.c.o
.PHONY : draw.o

# target to build an object file
draw.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/draw.c.o
.PHONY : draw.c.o

draw.i: draw.c.i
.PHONY : draw.i

# target to preprocess a source file
draw.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/draw.c.i
.PHONY : draw.c.i

draw.s: draw.c.s
.PHONY : draw.s

# target to generate assembly for a file
draw.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/draw.c.s
.PHONY : draw.c.s

event.o: event.c.o
.PHONY : event.o

# target to build an object file
event.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/event.c.o
.PHONY : event.c.o

event.i: event.c.i
.PHONY : event.i

# target to preprocess a source file
event.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/event.c.i
.PHONY : event.c.i

event.s: event.c.s
.PHONY : event.s

# target to generate assembly for a file
event.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/event.c.s
.PHONY : event.c.s

ewmh.o: ewmh.c.o
.PHONY : ewmh.o

# target to build an object file
ewmh.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/ewmh.c.o
.PHONY : ewmh.c.o

ewmh.i: ewmh.c.i
.PHONY : ewmh.i

# target to preprocess a source file
ewmh.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/ewmh.c.i
.PHONY : ewmh.c.i

ewmh.s: ewmh.c.s
.PHONY : ewmh.s

# target to generate assembly for a file
ewmh.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/ewmh.c.s
.PHONY : ewmh.c.s

mouse.o: mouse.c.o
.PHONY : mouse.o

# target to build an object file
mouse.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/mouse.c.o
.PHONY : mouse.c.o

mouse.i: mouse.c.i
.PHONY : mouse.i

# target to preprocess a source file
mouse.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/mouse.c.i
.PHONY : mouse.c.i

mouse.s: mouse.c.s
.PHONY : mouse.s

# target to generate assembly for a file
mouse.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/mouse.c.s
.PHONY : mouse.c.s

root.o: root.c.o
.PHONY : root.o

# target to build an object file
root.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/root.c.o
.PHONY : root.c.o

root.i: root.c.i
.PHONY : root.i

# target to preprocess a source file
root.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/root.c.i
.PHONY : root.c.i

root.s: root.c.s
.PHONY : root.s

# target to generate assembly for a file
root.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/root.c.s
.PHONY : root.c.s

screen.o: screen.c.o
.PHONY : screen.o

# target to build an object file
screen.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/screen.c.o
.PHONY : screen.c.o

screen.i: screen.c.i
.PHONY : screen.i

# target to preprocess a source file
screen.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/screen.c.i
.PHONY : screen.c.i

screen.s: screen.c.s
.PHONY : screen.s

# target to generate assembly for a file
screen.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/screen.c.s
.PHONY : screen.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/util.c.s
.PHONY : util.c.s

window.o: window.c.o
.PHONY : window.o

# target to build an object file
window.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/window.c.o
.PHONY : window.c.o

window.i: window.c.i
.PHONY : window.i

# target to preprocess a source file
window.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/window.c.i
.PHONY : window.c.i

window.s: window.c.s
.PHONY : window.s

# target to generate assembly for a file
window.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/window.c.s
.PHONY : window.c.s

xutil.o: xutil.c.o
.PHONY : xutil.o

# target to build an object file
xutil.c.o:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/xutil.c.o
.PHONY : xutil.c.o

xutil.i: xutil.c.i
.PHONY : xutil.i

# target to preprocess a source file
xutil.c.i:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/xutil.c.i
.PHONY : xutil.c.i

xutil.s: xutil.c.s
.PHONY : xutil.s

# target to generate assembly for a file
xutil.c.s:
	$(MAKE) -f CMakeFiles/ceres.dir/build.make CMakeFiles/ceres.dir/xutil.c.s
.PHONY : xutil.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ceres"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PyC.o"
	@echo "... PyC.i"
	@echo "... PyC.s"
	@echo "... atoms/atoms.o"
	@echo "... atoms/atoms.i"
	@echo "... atoms/atoms.s"
	@echo "... ceres.o"
	@echo "... ceres.i"
	@echo "... ceres.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... event.o"
	@echo "... event.i"
	@echo "... event.s"
	@echo "... ewmh.o"
	@echo "... ewmh.i"
	@echo "... ewmh.s"
	@echo "... mouse.o"
	@echo "... mouse.i"
	@echo "... mouse.s"
	@echo "... root.o"
	@echo "... root.i"
	@echo "... root.s"
	@echo "... screen.o"
	@echo "... screen.i"
	@echo "... screen.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
	@echo "... xutil.o"
	@echo "... xutil.i"
	@echo "... xutil.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

